# MkDocs Official Documentation

site_name: Curso Programación 10°
site_url: https://mydomain.org/mysite
repo_url: https://github.com/dan1elsaenz/programacion-10
repo_name: dan1elsaenz/programacion-10


theme:
  name: material

  language: es

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Cambiar a modo claro
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Cambiar a preferencia del sistema

  font:
    text: Roboto

  icon:
    logo: fontawesome/solid/laptop-code
    repo: fontawesome/brands/github

  favicon: assets/favicon.png

  features:
    - navigation.tabs
    - navigation.footer
    - content.footnote.tooltips
    # - navigation.sections # Expandir secciones
    - navigation.path
    - navigation.top
    - header.autohide
    - content.code.annotate
    - content.tabs.link
    - content.footnote.tooltips
    - content.code.copy
    - content.code.select
    - content.code.annotate


markdown_extensions:

  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
      - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dan1elsaenz
      name: dan1elsaenz
    - icon: fontawesome/solid/paper-plane
      link: mailto:dsaenzobando@gmail.com
      name: email
  generator: false


nav:
  - Inicio: README.md
  - Material del curso:
    - I Ciclo:
      - Clase 0. Introducción: material/i_ciclo/000/README.md
      - Clase 1. Conceptos básicos de Python: material/i_ciclo/001/README.md
      - Clase 2. Operadores, strings y estructura de control IF: material/i_ciclo/002/README.md
      - Clase 3. Listas y sus métodos: material/i_ciclo/003/README.md
      - Clase 4. Ejercicios de repaso y FOR loop: material/i_ciclo/004/README.md
      - Clase 5. Ejercicios de FOR loops: material/i_ciclo/005/README.md
      - Clase 6. WHILE loop: material/i_ciclo/006/README.md
      - Clase 7. Ejercicios de repaso: material/i_ciclo/007/README.md
      - Clase 8. Tuplas, diccionarios, sets: material/i_ciclo/008/README.md
      - Clase 9. Ejercicios de estructuras de datos: material/i_ciclo/009/README.md
      - Clase 10. Funciones: material/i_ciclo/010/README.md
      - Clase 11. Recursión y más estructuras de datos: material/i_ciclo/011/README.md
      - Clase 12. Algoritmos sobre números: material/i_ciclo/012/README.md
      - Clase 13. Estrategias de resolución, complejidad temporal y espacial: material/i_ciclo/013/README.md
      - Clase 14. Manejo de archivos, errores y uso de múltiples archivos fuente: material/i_ciclo/014/README.md
      - Clase 15. Repaso para el examen: material/i_ciclo/015/README.md
    - II Ciclo:
      - Clase 1. Repaso de conceptos anteriores: material/ii_ciclo/001/README.md
      - Clase 2. Introducción a OOP: material/ii_ciclo/002/README.md
      - Clase 3. Encapsulamiento de datos y herencia: material/ii_ciclo/003/README.md
      - Clase 4. Ejercicio de OOP: material/ii_ciclo/004/README.md
      - Clase 5. Polimorfismo, decoradores y sobrecarga de operadores: material/ii_ciclo/005/README.md
      - Clase 6. Programación funcional: material/ii_ciclo/006/README.md
      - Clase 7. Introducción a árboles binarios: material/ii_ciclo/007/README.md
      - Clase 8. Ejercicios de árboles binarios: material/ii_ciclo/008/README.md
      - Clase 9. Ejercicios sobre grafos: material/ii_ciclo/009/README.md
      - Clase 10. Uso de Git y GitHub: material/ii_ciclo/010/README.md

  - Tareas:
    - I Ciclo:
      - Tarea 1: tareas/i_ciclo/001/README.md
      - Tarea 2: tareas/i_ciclo/002/README.md
      - Tarea 3: tareas/i_ciclo/003/README.md
    - II Ciclo:
      - Tarea 1: tareas/ii_ciclo/001/README.md
      - Tarea 2: tareas/ii_ciclo/002/README.md
  - Prácticas Evaluadas:
    - I Ciclo:
      - Práctica 1: practicas_evaluadas/i_ciclo/001/README.md
      - Práctica 2: practicas_evaluadas/i_ciclo/002/README.md
      - Práctica 3: practicas_evaluadas/i_ciclo/003/README.md
      - Práctica 4: practicas_evaluadas/i_ciclo/004/README.md
    - II Ciclo:
      - Práctica 1: practicas_evaluadas/ii_ciclo/001/README.md
      - Práctica 2: practicas_evaluadas/ii_ciclo/002/README.md
      - Práctica 3: practicas_evaluadas/ii_ciclo/003/README.md
  - Exámenes:
    - I Ciclo:
      - Examen 1: examenes/i_ciclo/examen1/README.md
    # - II Ciclo:
  - OCI:
    - Programación dinámica: oci/programacion_dinamica/README.md
    - Backtracking: oci/backtracking/README.md
    - Grafos: oci/grafos/README.md

